   services:
     wireguard:
       image: linuxserver/wireguard
       container_name: wireguard
       cap_add:
         - NET_ADMIN
         - SYS_MODULE
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Moscow
         - SERVERURL=auto
         - SERVERPORT=51820
         - PEERS=3
         - PEERDNS=auto
         - INTERNAL_SUBNET=10.13.13.0
       volumes:
         - ./config:/config
         - /lib/modules:/lib/modules
       ports:
         - 51820:51820/udp
       restart: unless-stopped
       sysctls:
         - net.ipv4.conf.all.src_valid_mark=1
